name: Integration Tests

# These tests can only be run on `main` vs in PRs from forks
# because they require access to repo secrets. If the tests
# fail, videos will be uploaded to show what happened in the
# test browsers.
on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
    steps:
      # Sanity check to make sure the secrets are being injected properly
      - if: ${{ env.STRIPE_API_KEY == '' }}
        run: echo 'STRIPE_API_KEY env var is NOT set'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Build and Start Containers
        run: docker-compose up -d
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Integration Tests
        run: npm run test:integration
      # If the tests fail, upload videos of what happened
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Recordings
          path: test-results/
